options:
  max-time: 120

image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script
            # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            #- export IMAGE_NAME=adastradev/data-ingestion-agent:$BITBUCKET_COMMIT
            - export IMAGE_NAME=adastradev/data-ingestion-agent:latest

            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build -t $IMAGE_NAME .
            
            # Install prereqs for wait script
            - apt-get update
            - apt-get install -y jq

            # Waiting on docker to publish the new image from its automated build
            # and running system tests both rely on knowing the tag of the image.
            # Dockerhub takes the branch name and slightly mangles it to be used as
            # an image tag.
            - export NORMALIZED_DOCKER_TAG=`echo $BITBUCKET_BRANCH | sed -e "s|\/|_|"`

            - . ./pipeline/wait-for-latest-docker-image.sh

            # Run system test
            - . ./pipeline/run-system-tests.sh
    feature/*:
      - step:
          services:
            - docker
          script: 
            - export IMAGE_NAME=adastradev/data-ingestion-agent:automated-$BITBUCKET_COMMIT
            - docker build -t $IMAGE_NAME .

            # Install prereqs for wait script
            - apt-get update
            - apt-get install -y jq

            # Waiting on docker to publish the new image from its automated build
            # and running system tests both rely on knowing the tag of the image.
            # Dockerhub takes the branch name and slightly mangles it to be used as
            # an image tag.
            - export NORMALIZED_DOCKER_TAG=`echo $BITBUCKET_BRANCH | sed -e "s|\/|_|"`

            - . ./pipeline/wait-for-latest-docker-image.sh

            # Run system test
            - . ./pipeline/run-system-tests.sh
