options:
  max-time: 120

image: node:10

pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script:
            - export DISCOVERY_SERVICE=$DISCOVERY_SERVICE_PROD
            - export DEFAULT_STAGE=prod

            - export IMAGE_NAME=adastradev/data-ingestion-agent:latest

            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - . ./pipeline/build-docker-image.sh

            - docker tag $IMAGE_NAME $IMAGE_NAME
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME
    feature/*:
      - step:
          services:
            - docker
          script:
            - export DISCOVERY_SERVICE=$DISCOVERY_SERVICE_DEV
            - export DEFAULT_STAGE=dev
            - export NORMALIZED_DOCKER_TAG=`echo $BITBUCKET_BRANCH | sed -e "s|\/|_|"`
            - export IMAGE_NAME=data-ingestion-agent:$NORMALIZED_DOCKER_TAG
            - export REMOTE_IMAGE_NAME=adastradev/$IMAGE_NAME
            - echo IMAGE_NAME=$IMAGE_NAME -:- REMOTE_IMAGE_NAME=$REMOTE_IMAGE_NAME
            - . ./pipeline/build-docker-image.sh
            - docker tag $IMAGE_NAME $REMOTE_IMAGE_NAME
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $REMOTE_IMAGE_NAME

            # Install prereqs for wait script
            - apt-get update
            - apt-get install -y jq

            # Run system test
            - . ./pipeline/run-system-tests.sh

definitions:
  services:
    docker:
      memory: 2048 
