
docker build \
--build-arg DEFAULT_STAGE=$DEFAULT_STAGE \
--build-arg DISCOVERY_SERVICE=$DISCOVERY_SERVICE \
--build-arg ORACLE_ENDPOINT=$ORACLE_ENDPOINT \
--build-arg ORACLE_USER=$ORACLE_USER \
--build-arg ORACLE_PASSWORD=$ORACLE_PASSWORD \
--build-arg INTEGRATION_TESTS_ENABLED=true \
--build-arg COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN \
--build-arg COVERALLS_GIT_COMMIT=$BITBUCKET_COMMIT \
--build-arg COVERALLS_GIT_BRANCH=$BITBUCKET_BRANCH \
-t $IMAGE_NAME .
